### ISSUE TITLE
Integration to esp-open-rtos

### ISSUE THREAD

**Issue by andree182** [lujji/esp-httpd#1]
Hi! Awsome work - works out of box, was very easy to integrate into an existing project... I'll just add LWIP_HTTPD_CUSTOM_FILES to be able to use side-loaded files (via SPIFFS).

Anyhow, I'd say this would be a great addition to esp-open-rtos, where there's only http client so far. Have you considered it? It seems the license of httpd is compatible, so...

**Comment by andree182** [comment]
Ah, https://github.com/SuperHouse/esp-open-rtos/pull/324 ... It's there already, nevermind :)

**Comment by lujji** [comment]
I think most people would want to use SPIFFS by default, so I should at least update readme with instructions. Thanks.
