### ISSUE TITLE
Update makefsdata to save arrays on ROM 

### ISSUE THREAD

**Issue by gustavomassa** [lujji/esp-httpd#2]
Hello, first of all, nice job!

I was able to deploy the example perfectly. I'll update the makefsdata perl script to save strings on ROM and save some heap memory.
We need to add these 2 macros ICACHE_RODATA_ATTR STORE_ATTR after the array definition.
Edit these 2 lines of the makefsdata script:
```
print(OUTPUT "static const unsigned char data".$fvar."[] ICACHE_RODATA_ATTR STORE_ATTR = {\n");
print(OUTPUT "const struct fsdata_file file".$fvar."[] ICACHE_RODATA_ATTR STORE_ATTR = {{\n$prevfile,\ndata$fvar, ");
```

Thank you,
Best regards

**Comment by lujji** [comment]
That's a good point. Although the server was written mainly for esp-open-rtos which places constants in flash by default (see https://github.com/SuperHouse/esp-open-rtos/wiki/ESP-SDK-Differences#const-data-stored-in-flash). I suppose adding `ICACHE_RODATA_ATTR` attribute would increase portability, but as far as I know, flash requires 4-byte aligned word reads, which might be an issue when using official SDK.

**Comment by canab** [comment]
Hello, I am able to run the example on the official RTOS SDK with ICACHE_RODATA_ATTR STORE_ATTR attributes (and do not able to do so without them)
