### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by kiralikbeyin** [lujji/esp-httpd#4]
After 6-10 hours later esp doesnt get http requests. Serial monitor show other things like button pressed etc but no url info.

I saw this problem before in arduino platform but couldnt solve.

**Comment by lujji** [comment]
I haven't worked on this project for quite a while, however my ESPs were running for days without any problems. Could be a power related issue (e.g. voltage regulator overheating) or a memory leak perhaps.

**Comment by kiralikbeyin** [comment]
@lujji Thank you for reply

I found a real solution at last and people having these problem in every platform with ESP. I SPEND A FEW MOUNTHS for this problem.

**Browsers doesnt close connection. (yes i have header close connection)**

If i make a request with <a href=... this will kill ESP after 5 clients (or 5 requests) for a 300 bytes web page (works good with a few bytes)

If i make a request with **js xhr** everything is fine! You can set timeout etc everything.. Everybody looks to wrong place (like me) , problem is in browsers.



+++edit+++
refreshing every 60 sec recovers from non responding page. So you can still use hrefs..

js
````
	function refreshData()
	{
           location.reload();
	   setTimeout(refreshData, 60000);
	}
````
